/* Editable mithai catalogue. Add new sweets by copying one object and changing its fields. */
window.MITHAI_PRODUCTS = [
  {
    id: "p001",
    slug: "kaju-katli",
    name: "Kaju Katli",
    hindiName: "काजू कतली",
    category: "Dry Fruit",
    description: "Diamond-cut cashew fudge finished with delicate silver varq.",
    pricePerKg: 1280,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    tags: ["cashew", "premium", "gift", "festival"],
    emoji: "◇"
  },
  {
    id: "p002",
    slug: "motichoor-ladoo",
    name: "Motichoor Ladoo",
    hindiName: "मोतीचूर लड्डू",
    category: "Ghee-based",
    description: "Tiny saffron boondi pearls bound with pure ghee and cardamom.",
    pricePerKg: 620,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    tags: ["ladoo", "saffron", "wedding", "popular"],
    emoji: "●"
  },
  {
    id: "p003",
    slug: "besan-ladoo",
    name: "Besan Ladoo",
    hindiName: "बेसन लड्डू",
    category: "Ghee-based",
    description: "Slow-roasted gram flour ladoos with nutty aroma and warm ghee.",
    pricePerKg: 560,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["besan", "ladoo", "ghee", "classic"],
    emoji: "●"
  },
  {
    id: "p004",
    slug: "boondi-ladoo",
    name: "Boondi Ladoo",
    hindiName: "बूंदी लड्डू",
    category: "Ghee-based",
    description: "Traditional festive ladoos made with crisp golden boondi.",
    pricePerKg: 500,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["boondi", "ladoo", "prasad", "festival"],
    emoji: "●"
  },
  {
    id: "p005",
    slug: "gulab-jamun",
    name: "Gulab Jamun",
    hindiName: "गुलाब जामुन",
    category: "Milk-based",
    description: "Soft khoya dumplings soaked in fragrant rose-cardamom syrup.",
    pricePerKg: 480,
    minOrderGrams: 500,
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    tags: ["khoya", "syrup", "hot", "party"],
    emoji: "◉"
  },
  {
    id: "p006",
    slug: "rasgulla",
    name: "Rasgulla",
    hindiName: "रसगुल्ला",
    category: "Bengali",
    description: "Spongy chenna balls in light sugar syrup, chilled and fresh.",
    pricePerKg: 420,
    minOrderGrams: 500,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["chenna", "bengali", "syrup", "light"],
    emoji: "○"
  },
  {
    id: "p007",
    slug: "rasmalai",
    name: "Rasmalai",
    hindiName: "रसमलाई",
    category: "Bengali",
    description: "Chenna patties steeped in saffron milk with pistachio garnish.",
    pricePerKg: 760,
    minOrderGrams: 500,
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    tags: ["chenna", "rabri", "kesar", "chilled"],
    emoji: "◌"
  },
  {
    id: "p008",
    slug: "soan-papdi",
    name: "Soan Papdi",
    hindiName: "सोहन पापड़ी",
    category: "Festival Special",
    description: "Flaky, melt-in-mouth layers with cardamom and toasted nuts.",
    pricePerKg: 360,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["flaky", "gift", "diwali", "classic"],
    emoji: "▧"
  },
  {
    id: "p009",
    slug: "mathura-peda",
    name: "Peda (Mathura)",
    hindiName: "मथुरा पेड़ा",
    category: "Milk-based",
    description: "Caramelized khoya pedas with rustic Mathura-style richness.",
    pricePerKg: 620,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["khoya", "peda", "mathura", "milk"],
    emoji: "◍"
  },
  {
    id: "p010",
    slug: "kesar-peda",
    name: "Kesar Peda",
    hindiName: "केसर पेड़ा",
    category: "Milk-based",
    description: "Smooth milk pedas infused with saffron and cardamom.",
    pricePerKg: 700,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    tags: ["kesar", "peda", "saffron", "premium"],
    emoji: "◍"
  },
  {
    id: "p011",
    slug: "milk-barfi",
    name: "Barfi (Milk)",
    hindiName: "दूध बर्फी",
    category: "Milk-based",
    description: "Classic milk barfi with a fine-grained, creamy bite.",
    pricePerKg: 580,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["barfi", "milk", "classic", "gift"],
    emoji: "□"
  },
  {
    id: "p012",
    slug: "kalakand",
    name: "Kalakand",
    hindiName: "कलाकंद",
    category: "Milk-based",
    description: "Moist granular milk cake with gentle sweetness and nuts.",
    pricePerKg: 680,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["milk", "soft", "barfi", "fresh"],
    emoji: "▣"
  },
  {
    id: "p013",
    slug: "milk-cake",
    name: "Milk Cake",
    hindiName: "मिल्क केक",
    category: "Milk-based",
    description: "Slow-cooked milk sweet with caramel notes and layered texture.",
    pricePerKg: 720,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    tags: ["milk", "caramel", "premium", "gift"],
    emoji: "▣"
  },
  {
    id: "p014",
    slug: "gujiya",
    name: "Gujiya",
    hindiName: "गुझिया",
    category: "Festival Special",
    description: "Crisp festive pastry filled with mawa, coconut, and nuts.",
    pricePerKg: 760,
    minOrderGrams: 500,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["holi", "mawa", "festival", "gift"],
    emoji: "☾"
  },
  {
    id: "p015",
    slug: "jalebi",
    name: "Jalebi",
    hindiName: "जलेबी",
    category: "Ghee-based",
    description: "Crisp spirals fried fresh and dipped in saffron syrup.",
    pricePerKg: 360,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    tags: ["hot", "crispy", "breakfast", "syrup"],
    emoji: "◎"
  },
  {
    id: "p016",
    slug: "imarti",
    name: "Imarti",
    hindiName: "इमरती",
    category: "Ghee-based",
    description: "Flower-shaped urad dal sweet with a crisp syrupy finish.",
    pricePerKg: 420,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["urad", "crispy", "syrup", "festival"],
    emoji: "✺"
  },
  {
    id: "p017",
    slug: "balushahi",
    name: "Balushahi",
    hindiName: "बालूशाही",
    category: "Ghee-based",
    description: "Flaky glazed discs with a soft center and festive crunch.",
    pricePerKg: 520,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: false,
    tags: ["flaky", "syrup", "festival", "classic"],
    emoji: "◎"
  },
  {
    id: "p018",
    slug: "mysore-pak",
    name: "Mysore Pak",
    hindiName: "मैसूर पाक",
    category: "Ghee-based",
    description: "Rich gram flour sweet with a generous pure ghee crumb.",
    pricePerKg: 780,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    tags: ["ghee", "besan", "south indian", "premium"],
    emoji: "◆"
  },
  {
    id: "p019",
    slug: "sandesh",
    name: "Sandesh",
    hindiName: "संदेश",
    category: "Bengali",
    description: "Delicate chenna sweet with a light cardamom finish.",
    pricePerKg: 720,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["chenna", "bengali", "light", "fresh"],
    emoji: "◒"
  },
  {
    id: "p020",
    slug: "cham-cham",
    name: "Cham Cham",
    hindiName: "चम चम",
    category: "Bengali",
    description: "Soft chenna rolls with coconut and a gentle syrup glaze.",
    pricePerKg: 620,
    minOrderGrams: 500,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["chenna", "coconut", "bengali", "syrup"],
    emoji: "▬"
  },
  {
    id: "p021",
    slug: "gajar-halwa",
    name: "Gajar Halwa",
    hindiName: "गाजर हलवा",
    category: "Halwa",
    description: "Winter carrot halwa simmered with milk, ghee, and nuts.",
    pricePerKg: 620,
    minOrderGrams: 500,
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    tags: ["halwa", "carrot", "winter", "hot"],
    emoji: "▰"
  },
  {
    id: "p022",
    slug: "moong-dal-halwa",
    name: "Moong Dal Halwa",
    hindiName: "मूंग दाल हलवा",
    category: "Halwa",
    description: "Slow-roasted moong dal halwa fragrant with ghee and saffron.",
    pricePerKg: 740,
    minOrderGrams: 500,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["halwa", "moong", "ghee", "winter"],
    emoji: "▰"
  },
  {
    id: "p023",
    slug: "anjeer-roll",
    name: "Anjeer Roll",
    hindiName: "अंजीर रोल",
    category: "Dry Fruit",
    description: "Fig and nut roll with natural sweetness and premium crunch.",
    pricePerKg: 1480,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["fig", "dry fruit", "premium", "no added sugar"],
    emoji: "◖"
  },
  {
    id: "p024",
    slug: "pista-roll",
    name: "Pista Roll",
    hindiName: "पिस्ता रोल",
    category: "Dry Fruit",
    description: "Pistachio-rich rolls layered with cashew and cardamom.",
    pricePerKg: 1580,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    tags: ["pistachio", "cashew", "premium", "gift"],
    emoji: "◗"
  },
  {
    id: "p025",
    slug: "dry-fruit-ladoo",
    name: "Dry Fruit Ladoo",
    hindiName: "ड्राई फ्रूट लड्डू",
    category: "Dry Fruit",
    description: "Nut-and-date ladoos for a rich, wholesome festive bite.",
    pricePerKg: 1320,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["dates", "nuts", "ladoo", "premium"],
    emoji: "●"
  },
  {
    id: "p026",
    slug: "petha",
    name: "Petha",
    hindiName: "पेठा",
    category: "Festival Special",
    description: "Translucent ash gourd sweet with a refreshing soft chew.",
    pricePerKg: 340,
    minOrderGrams: 250,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["agra", "light", "syrup", "classic"],
    emoji: "◇"
  },
  {
    id: "p027",
    slug: "rabri",
    name: "Rabri",
    hindiName: "रबड़ी",
    category: "Milk-based",
    description: "Thickened milk with saffron, cardamom, and malai layers.",
    pricePerKg: 820,
    minOrderGrams: 500,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["milk", "malai", "kesar", "chilled"],
    emoji: "◌"
  },
  {
    id: "p028",
    slug: "malpua",
    name: "Malpua",
    hindiName: "मालपुआ",
    category: "Festival Special",
    description: "Soft fried pancakes soaked lightly in syrup and served festive.",
    pricePerKg: 560,
    minOrderGrams: 500,
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    tags: ["festival", "rabri", "syrup", "rajasthani"],
    emoji: "◓"
  }
];
